---
title: "Hypothesis testing"
author: "Tom Mushkat"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    code_folding: hide
    df_print: kable
    results: hide
    theme: readable
    toc: TRUE
    toc_float: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# One-ways
```{r, warning=FALSE, message=FALSE}

Data$emConditionOneWayAmount <- as.factor(Data$emCondition)
contrasts(Data$emCondition)
EMvsNoEM <- c(0.5, -1, 0.5)
ManyVSSingle <- c(0.5, 0, -0.5)
contrasts(Data$emConditionOneWayAmount) <- cbind(EMvsNoEM, ManyVSSingle)

Data$emConditionOneWayTrust <- as.factor(Data$emCondition)
contrasts(Data$emConditionOneWayTrust)
ManyVSNo <- c(0.5, -0.5, 0)
SinglevsOther <- c(-0.5, 1, -0.5)
contrasts(Data$emConditionOneWayTrust) <- cbind(SinglevsOther, ManyVSNo)

contrasts(Data$emConditionOneWayAmount)
contrasts(Data$emConditionOneWayTrust)

Data <- Data %>% 
  mutate(influencedByB = ifelse(howDecide == 'Right after the instructions', 'didntInfluence', 'Influenced'))

```

## Amount
```{r, warning=FALSE, message=FALSE}
Data %>% 
  mutate(emCondition = ordered(emCondition, levels = c('No', 'Single', 'Many'))) %>% 
  # filter(Order == 'amountFirst') %>% 
  group_by(emCondition) %>% 
  summarise(Mean = round(mean(Amount), 2),
            SD   = round(sd(Amount), 2))

Leven <- leveneTest(Data$Amount[Data$Order == 'amountFirst'] ~ Data$emCondition[Data$Order == 'amountFirst'])  # car packages
# Leven <- leveneTest(Data$Amount ~ Data$emCondition)  # car packages

trueVarTest <- ifelse(Leven$`Pr(>F)`[1] < 0.05, TRUE, FALSE)
Model <- aov(Amount ~ emCondition , data = Data)
Anova(Model, type = 'III', white.adjust = trueVarTest)

summary.lm(Model)



Data %>% 
  # filter(Order == 'questionFirst') %>% 
        mutate(emCondition = ordered(emCondition, levels = c('No', 'Single', 'Many'))) %>% 
  ggplot(aes(x = emCondition, y = Amount, fill = emCondition)) + 
    # geom_bar(stat = 'summary', position = position_dodge()) +
  geom_boxplot(color = 'purple', alpha = 2) + 
      geom_violin(alpha = 0.1) +
  scale_fill_manual(values = c('darkgrey', 'lightgrey', 'lightgreen')) +
  geom_jitter(aes(x = emCondition, y = Amount, fill = emCondition), color = 'blue') + 
    stat_summary(fun.data = mean_sdl, fun.args = list(mult = 1), 
               geom = "errorbar", color = "red", width = 0.2) +
    stat_summary(fun.y = mean, geom = "point", color = "red") +
    theme_classic() + ylab('Money') + xlab('Emoji level') + 
    ggtitle('One-Way ANOVA bar plot: Money by Emoji') +
  theme(plot.title = element_text(hjust = 0.5))

```

## Trust
```{r, warning=FALSE, message=FALSE}
Data %>% 
  filter(Order == 'questionFirst') %>% 
    mutate(emCondition = ordered(emCondition, levels = c('No', 'Single', 'Many'))) %>% 
  group_by(emCondition) %>% 
  summarise(Mean = round(mean(Trust), 2),
            SD   = round(sd(Trust), 2))

Leven1 <- leveneTest(Data$Trust[Data$Order == 'questionFirst'] ~ Data$emConditionOneWayTrust[Data$Order == 'questionFirst'])  # car packages
Leven2 <- leveneTest(Data$Trust[Data$Order == 'questionFirst'] ~ Data$mf[Data$Order == 'questionFirst'])  # car packages

trueVarTest <- ifelse(Leven1$`Pr(>F)`[1] < 0.05 | Leven1$`Pr(>F)`[1] < 0.05, TRUE, FALSE)
Model <- aov(Trust ~ emConditionOneWayTrust, data = Data[Data$Order == 'questionFirst', ])
Anova(Model, type = 'III', white.adjust = trueVarTest)
kruskal.test(Trust ~ emConditionOneWayTrust, data = Data[Data$Order == 'questionFirst', ])

summary.lm(Model)



Data %>% 
  # filter(Order == 'questionFirst') %>% 
  # filter(mf == 'Female') %>% 
    mutate(emCondition = ordered(emCondition, levels = c('No', 'Single', 'Many'))) %>% 
  ggplot(aes(x = emCondition, y = Trust, fill = emCondition)) + 
    # geom_bar(stat = 'summary', position = position_dodge()) +
  geom_boxplot(color = 'purple', alpha = 2) + 
      geom_violin(alpha = 0.1) +
  scale_fill_manual(values = c('darkgrey', 'lightgrey', 'lightgreen')) +
  geom_jitter(aes(x = emCondition, y = Trust, fill = emCondition), color = 'blue') + 
    stat_summary(fun.data = mean_sdl, fun.args = list(mult = 1), 
               geom = "errorbar", color = "red", width = 0.2) +
    stat_summary(fun.y = mean, geom = "point", color = "red") +
    theme_classic() + ylab('Trust') + xlab('Emoji level') + 
    ggtitle('One-Way ANOVA bar plot: Trust by Emoji') +
  theme(plot.title = element_text(hjust = 0.5))

pairwise.t.test(Data$Trust, Data$emCondition, p.adjust.method = 'BH', pool.sd = trueVarTest)
```

# Two-way
## Amount
```{r, warning=FALSE, message=FALSE}
Data %>% 
  group_by(emCondition, mf) %>% 
  summarise(Mean = round(mean(Amount), 2),
            SD   = round(sd(Amount), 2))


Leven1 <- leveneTest(Data$Amount ~ Data$emCondition)  # car packages
Leven2 <- leveneTest(Data$Amount ~ Data$mf)  # car packages
Leven3 <- leveneTest(Data$Amount ~ Data$emCondition:Data$mf)  # car packages

trueVarTest <- ifelse(Leven1$`Pr(>F)`[1] < 0.05 | Leven2$`Pr(>F)`[1] < 0.05 | Leven3$`Pr(>F)`[1] < 0.05, TRUE, FALSE)
Model <- aov(Amount ~ emCondition * mf, data = Data[Data$Amount != 0, ])
Anova(Model, type = 'III', white.adjust = trueVarTest)

Data %>% filter(Amount == 0)

Data %>% 
      mutate(emCondition = ordered(emCondition, levels = c('No', 'Single', 'Many'))) %>% 
  ggplot(aes(x = emCondition, y = Amount, fill = mf)) + 
    geom_bar(stat = 'summary', position = position_dodge()) +
    geom_boxplot(color = 'purple', alpha = 2, position = position_dodge(0.8)) + 
      geom_violin(alpha = 0.1, position = position_dodge(0.8)) +
  scale_fill_manual(values = c('darkgrey', 'lightgrey')) +
  # geom_jitter(aes(x = emCondition, y = Amount, fill = Order), color = 'blue') + 
     stat_summary(fun.data = mean_sdl, fun.args = list(mult = 1), 
               geom = "errorbar", color = "red", width = 0.2, position = position_dodge(0.8)) +
    stat_summary(fun.y = mean, geom = "point", color = "red", position = position_dodge(0.8)) +
    theme_classic() + ylab('Money') + xlab('Emoji level') + 
    ggtitle('Two-Way ANOVA bar plot: Money by Emoji') +
  theme(plot.title = element_text(hjust = 0.5))


Data %>% 
      mutate(emCondition = ordered(emCondition, levels = c('No', 'Single', 'Many'))) %>% 
  ggplot(aes(x = emCondition, y = Amount, fill = mf)) + 
    stat_summary(aes(group = mf, color = mf), fun.y = "mean", geom = "line", 
                 position = position_dodge(0.2)) + 
    stat_summary(fun.y = "mean", geom = "point", aes(color = mf), 
                 position = position_dodge(0.2)) + 
    stat_summary(fun.data = mean_sdl, geom = "errorbar", aes(color = mf),
                 position = position_dodge(0.2), width = 0.2) + 
    theme_classic() + ylab('Money') + xlab('Emoji level') + 
    ggtitle('Two-Way ANOVA: Money by Emoji * Order') + theme(plot.title = element_text(hjust = 0.5)) 

```

## Trust
```{r, warning=FALSE, message=FALSE}
Data %>% 
  group_by(emCondition) %>% 
  summarise(Mean = round(mean(Trust), 2),
            SD   = round(sd(Trust), 2),
            Max = max(Trust),
            Min = min(Trust))



Leven1 <- leveneTest(Data$Trust ~ Data$emCondition)  # car packages
Leven2 <- leveneTest(Data$Trust ~ Data$Order)  # car packages
Leven3 <- leveneTest(Data$Trust ~ Data$emCondition:Data$Order)  # car packages

Leven4 <- leveneTest(Data$Trust ~ Data$mf)  
Leven5 <- leveneTest(Data$Trust ~ Data$Religion)  


trueVarTest <- ifelse(Leven1$`Pr(>F)`[1] < 0.05 | Leven2$`Pr(>F)`[1] < 0.05 | Leven3$`Pr(>F)`[1] < 0.05 | Leven4$`Pr(>F)`[1] < 0.05 | Leven5$`Pr(>F)`[1] < 0.05, TRUE, FALSE)
Model <- aov(Trust ~ emCondition * Order, data = Data)
Anova(Model, type = 'III', white.adjust = trueVarTest)



Data %>% 
      mutate(emCondition = ordered(emCondition, levels = c('No', 'Single', 'Many'))) %>% 
  ggplot(aes(x = emCondition, y = Trust, fill = Order)) + 
    geom_bar(stat = 'summary', position = position_dodge(0.8)) +
  geom_boxplot(color = 'purple', alpha = 2, position = position_dodge(0.8)) + 
      geom_violin(alpha = 0.1, position = position_dodge(0.8)) +
  scale_fill_manual(values = c('darkgrey', 'lightgrey')) +
  # geom_jitter(aes(x = emCondition, y = Amount, fill = Order), color = 'blue') + 
     stat_summary(fun.data = mean_sdl, fun.args = list(mult = 1), 
               geom = "errorbar", color = "red", width = 0.2, position = position_dodge(0.8)) +
    stat_summary(fun.y = mean, geom = "point", color = "red", position = position_dodge(0.8)) +
    theme_classic() + ylab('Trust') + xlab('Emoji level') + 
    ggtitle('Two-Way ANOVA bar plot: Trust by Emoji') +
  theme(plot.title = element_text(hjust = 0.5))



Data %>% 
      mutate(emCondition = ordered(emCondition, levels = c('No', 'Single', 'Many'))) %>% 
  ggplot(aes(x = emCondition, y = Amount, fill = Order)) + 
    stat_summary(aes(group = Order, color = Order), fun.y = "mean", geom = "line", 
                 position = position_dodge(0.2)) + 
    stat_summary(fun.y = "mean", geom = "point", aes(color = Order), 
                 position = position_dodge(0.2)) + 
    stat_summary(fun.data = mean_sdl, geom = "errorbar", aes(color = Order),
                 position = position_dodge(0.2), width = 0.2) + 
    theme_classic() + ylab('Trust') + xlab('Emoji level') + 
    ggtitle('Two-Way ANOVA: Trust by Emoji * Order') + theme(plot.title = element_text(hjust = 0.5))
```





# Two-way influence * emoji no order
## Amount
```{r, warning=FALSE, message=FALSE}
Data %>% 
  group_by(emCondition, influencedByB) %>% 
  summarise(Mean = round(mean(Amount), 2),
            SD   = round(sd(Amount), 2),
            Max = max(Amount),
            Min = min(Amount),
            N = length(Amount))


Leven1 <- leveneTest(Data$Amount ~ Data$emCondition)  # car packages
Leven2 <- leveneTest(Data$Amount ~ Data$influencedByB)  # car packages
Leven3 <- leveneTest(Data$Amount ~ Data$emCondition:Data$influencedByB)  # car packages
Leven4 <- leveneTest(Data$Amount ~ Data$mf)  # car packages
# Leven5 <- leveneTest(Data$Amount ~ Data$Secular)  # car packages


trueVarTest <- ifelse(Leven1$`Pr(>F)`[1] < 0.05 | Leven2$`Pr(>F)`[1] < 0.05 | Leven3$`Pr(>F)`[1] < 0.05 | Leven4$`Pr(>F)`[1] < 0.05, TRUE, FALSE)
Model <- aov(Amount ~ emCondition * influencedByB * mf, data = Data)
Anova(Model, type = 'III', white.adjust = trueVarTest)


Data %>% 
      mutate(emCondition = ordered(emCondition, levels = c('No', 'Single', 'Many'))) %>% 
  ggplot(aes(x = emCondition, y = Amount, fill = influencedByB)) + 
    # geom_bar(stat = 'summary', position = position_dodge()) +
    geom_boxplot(aes(color = influencedByB), alpha = 0.1, position = position_dodge(0.8), size = 1) + 
      geom_violin(alpha = 0.1, position = position_dodge(0.8)) +
  scale_fill_manual(values = c('darkgrey', 'lightgrey')) +
  # geom_jitter(aes(x = emCondition, y = Amount, fill = Order), color = 'blue') + 
     stat_summary(fun.data = mean_sdl, fun.args = list(mult = 1), 
               geom = "errorbar", color = "purple", width = 0.2, position = position_dodge(0.8)) +
    stat_summary(fun.y = mean, geom = "point", color = "purple", position = position_dodge(0.8), size = 2) +
    theme_classic() + ylab('Money') + xlab('Emoji level') + 
    ggtitle('Two-Way ANOVA bar plot: Money by Emoji') +
  theme(plot.title = element_text(hjust = 0.5)) + 
  facet_grid(~mf)


Data %>% 
      mutate(emCondition = ordered(emCondition, levels = c('No', 'Single', 'Many'))) %>% 
  ggplot(aes(x = emCondition, y = Amount, fill = influencedByB)) + 
    stat_summary(aes(group = influencedByB, color = influencedByB), fun.y = "mean", geom = "line", 
                 position = position_dodge(0.2)) + 
    stat_summary(fun.y = "mean", geom = "point", aes(color = influencedByB), 
                 position = position_dodge(0.2)) + 
    stat_summary(fun.data = mean_sdl, geom = "errorbar", aes(color = influencedByB),
                 position = position_dodge(0.2), width = 0.2) + 
    theme_classic() + ylab('Money') + xlab('Emoji level') + 
    ggtitle('Two-Way ANOVA: Money by Emoji * influencedByB') + theme(plot.title = element_text(hjust = 0.5)) +
  facet_grid(~mf)

```

## Trust
```{r, warning=FALSE, message=FALSE}
Data %>% 
  group_by(emCondition, influencedByB) %>% 
  summarise(Mean = round(mean(Trust), 2),
            SD   = round(sd(Trust), 2),
            Max = max(Trust),
            Min = min(Trust),
            N = length(Trust))



Leven1 <- leveneTest(Data$Trust ~ Data$emCondition)  # car packages
Leven2 <- leveneTest(Data$Trust ~ Data$influencedByB)  # car packages
Leven3 <- leveneTest(Data$Trust ~ Data$emCondition:Data$influencedByB)  # car packages
Leven4 <- leveneTest(Data$Trust ~ Data$mf)  
Leven5 <- leveneTest(Data$Trust ~ Data$Secular)  


trueVarTest <- ifelse(Leven1$`Pr(>F)`[1] < 0.05 | Leven2$`Pr(>F)`[1] < 0.05 | Leven3$`Pr(>F)`[1] < 0.05 | Leven4$`Pr(>F)`[1] < 0.05 | Leven5$`Pr(>F)`[1] < 0.05, TRUE, FALSE)
Model <- aov(Trust ~ emCondition * influencedByB + mf + Secular + Motives, data = Data)
Anova(Model, type = 'III', white.adjust = trueVarTest)



Data %>% 
      mutate(emCondition = ordered(emCondition, levels = c('No', 'Single', 'Many'))) %>% 
  ggplot(aes(x = emCondition, y = Trust, fill = influencedByB)) + 
    # geom_bar(stat = 'summary', position = position_dodge()) +
    geom_boxplot(aes(color = influencedByB), alpha = 0.1, position = position_dodge(0.8), size = 1) + 
      geom_violin(alpha = 0.1, position = position_dodge(0.8)) +
  scale_fill_manual(values = c('darkgrey', 'lightgrey')) +
  # geom_jitter(aes(x = emCondition, y = Amount, fill = Order), color = 'blue') + 
     stat_summary(fun.data = mean_sdl, fun.args = list(mult = 1), 
               geom = "errorbar", color = "purple", width = 0.2, position = position_dodge(0.8)) +
    stat_summary(fun.y = mean, geom = "point", color = "purple", position = position_dodge(0.8), size = 2) +
    theme_classic() + ylab('Trust') + xlab('Emoji level') + 
    ggtitle('Two-Way ANOVA bar plot: Trust by Emoji') +
  theme(plot.title = element_text(hjust = 0.5)) +
  facet_grid(~mf)



Data %>% 
      mutate(emCondition = ordered(emCondition, levels = c('No', 'Single', 'Many'))) %>% 
  ggplot(aes(x = emCondition, y = Trust, fill = influencedByB)) + 
    stat_summary(aes(group = influencedByB, color = influencedByB), fun.y = "mean", geom = "line", 
                 position = position_dodge(0.2)) + 
    stat_summary(fun.y = "mean", geom = "point", aes(color = influencedByB), 
                 position = position_dodge(0.2)) + 
    stat_summary(fun.data = mean_sdl, geom = "errorbar", aes(color = influencedByB),
                 position = position_dodge(0.2), width = 0.2) + 
    theme_classic() + ylab('Trust') + xlab('Emoji level') + 
    ggtitle('Two-Way ANOVA: Trust by Emoji * influencedByB') + theme(plot.title = element_text(hjust = 0.5)) +
  facet_grid(~mf)
```

